#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    conexao.dados_residuais = b''
    if dados == b'':
        return sair(conexao)
    #Junte de dados residuais + dados novos
    linhas = (conexao.dados_residuais + dados).split(b'\n')
    #Processamento das linhas
    for linha in linhas:
    #CASOS:    
        #PING
        if linha.startswith(b'PING'):
            partes = linha.split(b' ',1)
            if len(partes) > 1:
            	conexao.enviar(b':server PONG server :' + partes[1] + b'\n')
            else:
                conexao.enviar(b':server PONG server :\n')
    #conexao.dados_residuais=b''
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
